# generated by datamodel-codegen:
#   filename:  omnirag.openapi.yaml
#   timestamp: 2025-10-17T22:24:04+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class Status(Enum):
    queued = "queued"
    processing = "processing"
    ready = "ready"
    error = "error"


class Document(BaseModel):
    doc_id: UUID
    sha256: str
    mime: str
    pages: int
    source_uri: str
    doc_name: str
    ingest_run_id: UUID
    doc_type: str
    status: Status
    version: int
    created_at: datetime
    tenant_id: UUID
    embedding_id: str


class CitationSpan(BaseModel):
    chunk_span: Optional[List[int]] = Field(None, max_length=2, min_length=2)
    page: Optional[int] = None
    evidence_id: Optional[str] = None


class RetrievalPlan(BaseModel):
    dense: Optional[bool] = None
    sparse: Optional[bool] = None
    graph_hops: Optional[int] = None


class RetrievalResult(BaseModel):
    query_id: UUID
    chunk_id: UUID
    score: float
    rerank_score: float
    citation_spans: List[CitationSpan]
    filters: Dict[str, Any]
    retrieval_plan: RetrievalPlan


class Citation(BaseModel):
    doc_id: Optional[UUID] = None
    chunk_id: Optional[UUID] = None
    page: Optional[int] = None
    span: Optional[List[int]] = Field(None, max_length=2, min_length=2)
    evidence_id: Optional[str] = None


class Relation(BaseModel):
    rel_id: Optional[str] = None
    type: Optional[str] = None
    weight: Optional[float] = None


class Support(BaseModel):
    entities: Optional[List[str]] = None
    relations: Optional[List[Relation]] = None


class Answer(BaseModel):
    text: str
    citations: List[Citation]
    support: Support
    confidence: float


class Graph(BaseModel):
    seed_entities: Optional[List[str]] = None
    hops: Optional[int] = None
    rel_types: Optional[List[str]] = None


class QueryRequest(BaseModel):
    q: str
    k: Optional[int] = 10
    filters: Optional[Dict[str, Any]] = None
    graph: Optional[Graph] = None
    rerank: Optional[bool] = False
    require_citations: Optional[bool] = True


class Retrieval(BaseModel):
    dense: Optional[bool] = None
    sparse: Optional[bool] = None
    graph_hops: Optional[int] = None


class QueryResponse(BaseModel):
    query_id: UUID
    answers: List[Answer]
    retrieval: Retrieval
    retrieval_details: Optional[RetrievalResult] = None
    trace_id: UUID


class Step(BaseModel):
    t: Optional[datetime] = None
    step: Optional[str] = None
    lat_ms: Optional[int] = None
    k: Optional[int] = None
    model: Optional[str] = None
    hops: Optional[int] = None
    start_node_ids: Optional[List[str]] = None


class Citation1(BaseModel):
    sentence_ix: Optional[int] = None
    chunk_id: Optional[UUID] = None
    page: Optional[int] = None
    span: Optional[List[int]] = Field(None, max_length=2, min_length=2)


class Trace(BaseModel):
    trace_id: UUID
    query_id: UUID
    steps: List[Step]
    tools_used: List[str]
    citations: List[Citation1]
    agent_plan: Dict[str, Any]
    version: int


class Problem(BaseModel):
    type: AnyUrl = Field(..., description="URI reference identifying the problem type")
    title: str = Field(..., description="Short, human-readable summary")
    status: int = Field(..., description="HTTP status code")
    code: Optional[str] = Field(None, description="Application-specific error code")
    trace_id: Optional[str] = Field(None, description="Request trace identifier")
    details: Optional[Dict[str, Any]] = Field(
        None, description="Additional problem-specific details"
    )


class HealthResponse(BaseModel):
    status: str
    version: str
    git_sha: str
